name: vtb_hackathon
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.1
  flutter_svg: ^0.22.0
  intl: ^0.17.0
  syncfusion_flutter_charts: ^19.3.44+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/good_cat.png
    - assets/images/bad_cat.png
    - assets/images/logo.png
    - assets/images/grechka.jpg
    
    - lib/assets/icons/flame.svg
    - lib/assets/icons/home.svg
    - lib/assets/icons/finance.svg
    - lib/assets/icons/other_horizontal.svg
    - lib/assets/icons/target.svg
    - lib/assets/icons/time.svg
    - lib/assets/icons/pie_chart.svg
    - lib/assets/icons/dash.svg
    - lib/assets/icons/plus.svg
    - lib/assets/icons/minus.svg

    - lib/assets/images/profit.png
    - lib/assets/images/not_stonks.png

